### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by RichY0608** [fuqiuluo/CxKittyForAndroid#2]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
A clear and concise description o
![Uploading Screenshot_20241202_192749.jpg…]()
f any alternative solutions or features you've considered.

**Additional context**

**Comment by fuqiuluo** [comment]
你这个图片看不见

**Comment by fuqiuluo** [comment]
还在上传中，你就点提交了

**Comment by RichY0608** [comment]
![Screenshot_20241202_192749](https://github.com/user-attachments/assets/8e8612e0-8135-439d-86d7-f4f7e7e38d4c)

**Comment by fuqiuluo** [comment]
这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷

**Comment by RichY0608** [comment]
> 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷

考试模式显示这个

**Comment by fuqiuluo** [comment]
> > 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷
> 
> 考试模式显示这个

你应该找CxKitty的作者（

**Comment by RichY0608** [comment]
麻烦更新一下git 作者修复过了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上7:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2)




   
这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷
  
考试模式显示这个
  
你应该找CxKitty的作者（

**Comment by fuqiuluo** [comment]
> 麻烦更新一下git 作者修复过了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月2日(周一) 晚上7:43 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷 考试模式显示这个 你应该找CxKitty的作者（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

我没有作者的CxKitty仓库，更新直接改https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip，这个压缩包就好了，里面放的是cxkitty的源代码，cxkitty依赖的py环境在boot.zip里面

**Comment by RichY0608** [comment]
哥 给个联系方式 方便点



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上10:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2)




  
麻烦更新一下git 作者修复过了
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月2日(周一) 晚上7:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷 考试模式显示这个 你应该找CxKitty的作者（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我没有作者的CxKitty仓库，更新直接改https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip，这个压缩包就好了，里面放的是cxkitty的源代码，cxkitty依赖的py环境在boot.zip里面

**Comment by fuqiuluo** [comment]
> 哥 给个联系方式 方便点
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月2日(周一) 晚上10:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 麻烦更新一下git 作者修复过了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月2日(周一) 晚上7:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷 考试模式显示这个 你应该找CxKitty的作者（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 我没有作者的CxKitty仓库，更新直接改[https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip，这个压缩包就好了，里面放的是cxkitty的源代码，cxkitty依赖的py环境在boot.zip里面](https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%8E%8B%E7%BC%A9%E5%8C%85%E5%B0%B1%E5%A5%BD%E4%BA%86%EF%BC%8C%E9%87%8C%E9%9D%A2%E6%94%BE%E7%9A%84%E6%98%AFcxkitty%E7%9A%84%E6%BA%90%E4%BB%A3%E7%A0%81%EF%BC%8Ccxkitty%E4%BE%9D%E8%B5%96%E7%9A%84py%E7%8E%AF%E5%A2%83%E5%9C%A8boot.zip%E9%87%8C%E9%9D%A2) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

一样的,mut@vip.qq.com

**Comment by RichY0608** [comment]
哥加一下你QQ git加载的慢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月2日(周一) 晚上11:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2)




  
哥 给个联系方式 方便点
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月2日(周一) 晚上10:57 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 麻烦更新一下git 作者修复过了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月2日(周一) 晚上7:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷 考试模式显示这个 你应该找CxKitty的作者（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt; 我没有作者的CxKitty仓库，更新直接改https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip，这个压缩包就好了，里面放的是cxkitty的源代码，cxkitty依赖的py环境在boot.zip里面 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.&gt;
  
一样的

**Comment by fuqiuluo** [comment]
> 哥 给个联系方式 方便点
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年12月2日(周一) 晚上10:57 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 麻烦更新一下git 作者修复过了 … ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年12月2日(周一) 晚上7:43 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2) 这个是CxKitty那边的错误吧，是你的题没有答，没有答题不能往下刷 考试模式显示这个 你应该找CxKitty的作者（ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt; 我没有作者的CxKitty仓库，更新直接改[https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip，这个压缩包就好了，里面放的是cxkitty的源代码，cxkitty依赖的py环境在boot.zip里面](https://github.com/fuqiuluo/CxKittyForAndroid/blob/main/app/src/main/cpp/bootstrap-aarch64.zip%EF%BC%8C%E8%BF%99%E4%B8%AA%E5%8E%8B%E7%BC%A9%E5%8C%85%E5%B0%B1%E5%A5%BD%E4%BA%86%EF%BC%8C%E9%87%8C%E9%9D%A2%E6%94%BE%E7%9A%84%E6%98%AFcxkitty%E7%9A%84%E6%BA%90%E4%BB%A3%E7%A0%81%EF%BC%8Ccxkitty%E4%BE%9D%E8%B5%96%E7%9A%84py%E7%8E%AF%E5%A2%83%E5%9C%A8boot.zip%E9%87%8C%E9%9D%A2) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

1372362033

**Comment by RichY0608** [comment]
通过下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年12月3日(周二) 凌晨0:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [fuqiuluo/CxKittyForAndroid] 报错 (Issue #2)




 
Closed #2 as not planned.
